version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name Myworkapp --s3-location s3://myworkbucket000/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src
